/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roda.a.roda;

import javax.swing.JLabel;

/**
 *
 * @author JoãoCarlos
 */
public class telaJogo extends javax.swing.JFrame {
    
    public telaJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLtema = new javax.swing.JLabel();
        jLpalavra = new javax.swing.JLabel();
        jLscore2 = new javax.swing.JLabel();
        jLs2 = new javax.swing.JLabel();
        jLscore1 = new javax.swing.JLabel();
        jLs1 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        resultado.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(resultado);
        resultado.setBounds(270, 290, 120, 60);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JoãoCarlos\\Desktop\\AP2\\Imagens Roda a Roda\\roda.png")); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 180, 320, 280);

        jLtema.setForeground(new java.awt.Color(255, 255, 255));
        jLtema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLtema);
        jLtema.setBounds(200, 10, 100, 20);

        jLpalavra.setBackground(new java.awt.Color(255, 255, 255));
        jLpalavra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLpalavra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLpalavra.setOpaque(true);
        getContentPane().add(jLpalavra);
        jLpalavra.setBounds(50, 50, 400, 90);

        jLscore2.setOpaque(true);
        getContentPane().add(jLscore2);
        jLscore2.setBounds(30, 380, 140, 30);

        jLs2.setBackground(new java.awt.Color(204, 0, 51));
        jLs2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLs2.setText("     Jogador 2:");
        jLs2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLs2.setOpaque(true);
        getContentPane().add(jLs2);
        jLs2.setBounds(20, 360, 160, 60);

        jLscore1.setOpaque(true);
        getContentPane().add(jLscore1);
        jLscore1.setBounds(30, 290, 140, 30);

        jLs1.setBackground(new java.awt.Color(0, 204, 102));
        jLs1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLs1.setText("     Jogador 1:");
        jLs1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLs1.setOpaque(true);
        getContentPane().add(jLs1);
        jLs1.setBounds(20, 270, 160, 60);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roda/a/roda/telaJogo.png"))); // NOI18N
        fundo.setOpaque(true);
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Roda roda = new Roda();
        framePalpite fp = new framePalpite();
        
        roda.rodar();
        resultado.setText(" "+roda.resultPrint);
        fp.setVisible(true);
        fp.setSize(342, 167);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLpalavra;
    private javax.swing.JLabel jLs1;
    private javax.swing.JLabel jLs2;
    private javax.swing.JLabel jLscore1;
    private javax.swing.JLabel jLscore2;
    public javax.swing.JLabel jLtema;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLpalavra() {
        return jLpalavra;
    }

    public void setjLpalavra(JLabel jLpalavra) {
        this.jLpalavra = jLpalavra;
    }


}
