/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roda.a.roda;

/**
 *
 * @author JoãoCarlos
 */
public class Tela2 extends javax.swing.JFrame {
       
    public Tela2() {
        initComponents();
        setTitle("Roda a Roda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBut2jog = new javax.swing.JButton();
        jButHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jBut2jog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBut2jog.setText("2 Jogadores");
        jBut2jog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut2jogActionPerformed(evt);
            }
        });
        getContentPane().add(jBut2jog);
        jBut2jog.setBounds(270, 60, 170, 40);

        jButHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\JoãoCarlos\\Desktop\\AP2\\Imagens Roda a Roda\\Icon Home.png")); // NOI18N
        jButHome.setBorder(null);
        jButHome.setBorderPainted(false);
        jButHome.setContentAreaFilled(false);
        jButHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButHomeActionPerformed(evt);
            }
        });
        getContentPane().add(jButHome);
        jButHome.setBounds(10, 10, 50, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\JoãoCarlos\\Desktop\\AP2\\Imagens Roda a Roda\\rrMenuSemLogo.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -30, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButHomeActionPerformed
        
        TelaInicio tela1 = new TelaInicio();
        tela1.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButHomeActionPerformed

    private void jBut2jogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut2jogActionPerformed

        Jogadores j = new Jogadores();
        telaNomeJog tnj = new telaNomeJog();

        j.qtdJog = 2;

        tnj.setVisible(true);
        tnj.setSize(500, 500);
        dispose();

    }//GEN-LAST:event_jBut2jogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut2jog;
    private javax.swing.JButton jButHome;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
